server:
  port: 8082

dubbo:
  application:
    name: application-customer
  protocol:
    id: dubbo
    port: 20880
  registry:
    id: application-customer
    address: zookeeper://127.0.0.1:2181
  consumer:
    check: false

elasticjob:
  regCenter:
    serverLists: 127.0.0.1:2181
    namespace: elasticjob-lite-springboot
  jobs:
    MyDataJob:
      elasticJobClass: org.apache.shardingsphere.elasticjob.dataflow.job.DataflowJob
      cron: 0 0/1 * * * ?
      shardingTotalCount: 3
      shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou
      overwrite: true
      failover: false
      props:
        streaming.process: true
