server:
  port: 8082

dubbo:
  application:
    name: application-customer
  protocol:
    id: dubbo
    port: 20880
  registry:
    id: application-customer
    address: zookeeper://127.0.0.1:2181
  consumer:
    check: false
